# Dataset configuration
dataset:
  data_dir: "data/pcam"
  batch_size: 32
  num_workers: 4
  image_size: 96

# Model configurations to benchmark
models:
  - name: "google/vit-base-patch16-224"
    num_classes: 2
    learning_rate: 0.0001
    weight_decay: 0.01

# Training configuration
training:
  max_epochs: 10
  accelerator: "cpu"  # Changed to CPU since no GPU is available
  devices: 1
  strategy: "auto"  # Set strategy to auto
  precision: 32

# Logging configuration
logging:
  project_name: "pcam-benchmark"
  save_dir: "logs"
  log_every_n_steps: 50
